# Generated by Django 3.1.1 on 2020-10-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('ING', 'Ingenieria'), ('SCI', 'Ciencias'), ('HUM', 'Humanidades'), ('SOC', 'Ciencias Sociales')], default='ING', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('ciudad', models.CharField(max_length=64)),
                ('abv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('SUS', 'Suspendido'), ('BAJA', 'Dado de baja')], default='ACT', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('BACH', 'Bachillerato'), ('LIC', 'Licenciatura'), ('MAS', 'Maestría'), ('DOC', 'Doctorado'), ('POSD', 'Post-doctorado')], default='MAS', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('clave', models.CharField(max_length=8)),
                ('creditos', models.IntegerField()),
                ('horas_semanales', models.IntegerField()),
                ('ofertada_antes', models.BooleanField()),
                ('alumnos_previo', models.IntegerField()),
                ('abierta', models.BooleanField()),
                ('no_estudiantes', models.IntegerField()),
                ('grupos', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolCRUD.area')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.CharField(max_length=9)),
                ('nss', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=64)),
                ('rfc', models.CharField(max_length=16)),
                ('curp', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=64)),
                ('email_personal', models.CharField(max_length=64)),
                ('email_institucional', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=32)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schoolCRUD.area')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolCRUD.estado')),
                ('materias', models.ManyToManyField(to='schoolCRUD.Materia')),
                ('ultimo_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolCRUD.grado')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(to='schoolCRUD.Profesor'),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('abv', models.CharField(max_length=4)),
                ('semestres', models.IntegerField()),
                ('alumnos_inscritos', models.IntegerField()),
                ('fecha_plan', models.DateField()),
                ('creditos_min', models.IntegerField()),
                ('creditos_max', models.IntegerField()),
                ('campus', models.ManyToManyField(to='schoolCRUD.Campus')),
                ('materias', models.ManyToManyField(to='schoolCRUD.Materia')),
                ('profesores', models.ManyToManyField(to='schoolCRUD.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=128)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(max_length=64)),
                ('curp', models.CharField(max_length=64)),
                ('lugar_nacimiento', models.CharField(max_length=64)),
                ('tutor', models.CharField(max_length=64)),
                ('semestre', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolCRUD.carrera')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolCRUD.estado')),
                ('historial_aprobadas', models.ManyToManyField(related_name='aprobadas', to='schoolCRUD.Materia')),
                ('historial_reprobadas', models.ManyToManyField(related_name='repsrobadas', to='schoolCRUD.Materia')),
            ],
        ),
    ]
